language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
env:
  - INSTALL_FLAG=--global
  - INSTALL_FLAG=
install:
  - npm install $INSTALL_FLAG
cache:
  directories:
    - "node_modules"
services:
  - mongodb
