language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
env:
  - GLOBAL_INSTALL_FLAG=--global
  - GLOBAL_INSTALL_FLAG=
install:
  - npm install $GLOBAL_INSTALL_FLAG
cache:
  directories:
    - "node_modules"
services:
  - mongodb
