#Automatically generating npm conda package
{% set data = load_npm() %}
package:
  name: {{data.get('name').lower()}}
  version: {{data.get('version')}}

source:
  git_url: .. # relative to recipe dir
  git_rev: e9e472c8f5850e05c6f555aef3eb10c0d968109c

build:
  number: {% block build_number %}1{% endblock %}
  script:
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile
    - env
    - ls -lah conda-recipe
    - ls -lah "$SRC_DIR"/conda-recipe/
    - mkdir -p "$PREFIX"/conda/etc/activate.d/
    - mkdir -p "$PREFIX"/conda/etc/deactivate.d/
    - cp "$SRC_DIR"/conda-recipe/mountainlab_activate.sh "$PREFIX"/conda/etc/activate.d/
    - cp "$SRC_DIR"/conda-recipe/mountainlab_deactivate.sh "$PREFIX"/conda/etc/deactivate.d/

requirements:
  build:
    - nodejs

  run:
    - nodejs

test:
  commands:
    - npm list -g mountainlab-js
    - ml-config
  requires:
    - nodejs

about:
  home: {{data.get('repository').get('url')}}
  license: {{data.get('license')}}

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
